DROP TABLE IF EXISTS `rc_app_config`;
CREATE TABLE `rc_app_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `android_income_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'android我的收益开关',
  `ios_income_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'ios我的收益开关',
  `android_operation_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'android运营位开关',
  `ios_operation_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'ios运营位开关',
  `operation_time` int(11) NOT NULL DEFAULT '0' COMMENT '运营位时间范围',
  `android_version` int(11) NOT NULL DEFAULT '0' COMMENT 'android版本号',
  `ios_version` int(11) NOT NULL DEFAULT '0' COMMENT 'ios版本号',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `interval_hour` int(11) NOT NULL,
  `show_number` int(11) NOT NULL,
  `next_time` int(11) NOT NULL DEFAULT '0' COMMENT 'next 点击时间',
  `boy_active_auto` tinyint(4) NOT NULL DEFAULT '0' COMMENT '男性自动active开关',
  `girl_active_auto` tinyint(4) NOT NULL DEFAULT '0' COMMENT '女性自动active开关',
  `hot_user_min_stone_num` int(11) DEFAULT '1000' COMMENT 'hot用户最低钻石数',
  `top_user_num` int(11) DEFAULT '50' COMMENT 'top榜单数量',
  `top_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'top榜开关 0 打开 1 关闭',
  `active_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'active开关 0 打开 1 关闭',
  `home_snapshot` int(11) NOT NULL DEFAULT '1' COMMENT '女性首页截图次数',
  `invitation_gold_num` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '邀请好友添加金币数量',
  `match_wait_time` tinyint(4) NOT NULL DEFAULT '10' COMMENT '匹配等待时间',
  `platform_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '平台类型',
  `match_quit_time` int(11) NOT NULL DEFAULT '0' COMMENT '匹配进入视频X秒后可以切人或者退出',
  `match_friend_button_time` int(11) NOT NULL DEFAULT '0' COMMENT '匹配进入视频X后，加好友按钮出现',
  `match_like_button_time` int(11) NOT NULL DEFAULT '0' COMMENT '匹配进入视频X秒后，点赞按钮出现',
  `app_id` int(11) NOT NULL DEFAULT '0' COMMENT '应用id',
  `gold_show_match_time` int(11) NOT NULL DEFAULT '0' COMMENT '筛选引导金币包出现匹配次数',
  `sex_selection_match_time` int(11) NOT NULL DEFAULT '0' COMMENT '设置匹配次数 弹出性别筛选次数的显示框',
  `girl_gap_match_time` int(11) DEFAULT NULL COMMENT '匹配到女引导间隔N个女',
  `request_no_time` int(11) DEFAULT NULL COMMENT '请不到人次数',
  `request_time` int(11) DEFAULT NULL COMMENT '请求间隔',
  `text_translate` tinyint(4) NOT NULL DEFAULT '0' COMMENT '文字翻译开关 0 打开 1 关闭',
  `video_translate` tinyint(4) NOT NULL DEFAULT '0' COMMENT '视频翻译开关 0 打开 1 关闭',
  `bury_record_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT '埋点开关  0 打开 1 关闭',
  `index_commodity_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT '首页金币包开关  0 打开 1 关闭',
  `goddess_not_match_time` int(11) NOT NULL DEFAULT '0' COMMENT '女神模式下多少秒匹配不到，则展示提示',
  `goddess_quit_time` int(11) NOT NULL DEFAULT '0' COMMENT '女神来电挂断时间',
  `goddess_event_record_switch` tinyint(4) NOT NULL DEFAULT '1' COMMENT '女神视频事件记录开关',
  `friend_bury_record_switch` tinyint(4) NOT NULL DEFAULT '1' COMMENT '好友埋点记录开关',
  `bury_record_switch_all` tinyint(4) NOT NULL DEFAULT '1' COMMENT '埋点上传开关最新 0:开,1:关',
  `h5_switch` tinyint(4) DEFAULT '0' COMMENT 'h5开关',
  `web_pay_tips` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'web 充值提示引导开关 0 打开 1 关闭 ',
  `web_pay_tips_country` varchar(255) NOT NULL DEFAULT '' COMMENT 'web 充值提示引导开关支持国家',
  `goddess_video_show_range` varchar(50) NOT NULL DEFAULT '' COMMENT '女神视频展示规则 格式为 最小值(int)-最大值(int)',
  `recharge_activity_switch` tinyint(4) DEFAULT '0' COMMENT '充值开关活动',
  `back_time` tinyint(4) DEFAULT '0' COMMENT '视屏扣费离开时间',
  `translate_times` tinyint(4) DEFAULT '0' COMMENT '翻译次数',
  `match_video_filter_switch` tinyint(4) NOT NULL DEFAULT '1' COMMENT '匹配视频过滤开关 0 关闭 1 打开',
  `other_video_filter_switch` tinyint(4) NOT NULL DEFAULT '1' COMMENT '非匹配视频过滤开关 0 关闭 1 打开',
  `third_pay_redirect_url` varchar(100) DEFAULT NULL COMMENT '三方支付重定向地址',
  `ad_switch` tinyint(4) DEFAULT '0' COMMENT '广告开关:0 关闭 1打开',
  `recommend_switch` tinyint(1) DEFAULT '0' COMMENT '推荐开关:0 关闭 1打开',
  `mobile_login_switch` tinyint(4) NOT NULL DEFAULT '0' COMMENT '手机号登录开关 0关闭 1打开',
  `free_hand_time` int(2) DEFAULT NULL COMMENT '闪聊免费模式可挂断电话时间，单位秒',
  `pay_hand_time` int(2) DEFAULT NULL COMMENT '闪聊付费模式可挂断电话时间，单位秒',
  `quick_chat_free_time` int(2) DEFAULT NULL COMMENT '闪聊模式免费时长',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
